### ISSUE TITLE
Cannot unpack and determine

### ISSUE THREAD

**Issue by Antwnina** [hellupline/flask-manager#1]
sudo pip install https://github.com/hellupline/flask-manager.git
The directory '/home/antonina/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/antonina/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting https://github.com/hellupline/flask-manager.git
  Downloading https://github.com/hellupline/flask-manager.git
     \ 61kB 191kB/s
  Cannot unpack file /tmp/pip-ox_7xg-unpack/flask-manager.git (downloaded from /tmp/pip-gqPcJq-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-gqPcJq-build

**Comment by hellupline** [comment]
The install instructions where wrong, this [Pull Request](https://github.com/hellupline/flask-manager/pull/2) fixed it, it should be pip install git+https://github.com/hellupline/flask-manager.git

but beware, I created this to help me in a specific situation on a project I worked, I do not actively maintain it anymore, though it may be useful to learn something in Flask, Jinja2, etc, 

Tip: use virtualenv, or at least pip install --user

thank you for your issue :)
